druid:
  url: jdbc:mysql://47.100.250.62:3306/tropical?characterEncoding=UTF-8&allowMultiQueries=true
  username: patrick
  password: EetLXUQHm5IFbv/oboBNKTPO+hDHz7RuQi4QKSl7Yn7vk3D3w8eAEC9RBHot/U3idZgfnyNJlq0dhYPPj/zCsw==
  publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJla3X4KYqfMYtzmxBsOi/JuB8zPhgk0bVfVIjE8iJiZomzW7DixVl1FIl2umXtulqKBxgcaPGkSx+h6n1xLvj8CAwEAAQ==
  initialSize: 1
  minIdle: 1
  maxActive: 20
  maxWait: 60000

jwt:
  alg: HS256
  type: jwt
  privateSecret: ABSEFG123456

spring:
  redis:
    host: 47.100.250.62
    port: 6379
    password: Beconfident1
    poolMaxTotal: 100
    poolMaxIdle: 50
    poolMaxWait: 50
    timeout: 5000ms
    jedis:
      pool:
        min-idle: 1
